### PR TITLE
eslint 2.0 compability

### PR DESCRIPTION
**Pull request by marudor**
Probably Quick and Dirty way but this enables eslint 2.0 compability

### CODE REVIEW

**Comment by gajus** [comment]
@zertosh Is there any reason to not merge this?

**Comment by zertosh** [comment]
Sorry for the delay - I'll go through this tonight. I haven't had a chance to look at the eslint 2.0 API changes (more precisely escope), and babel-eslint 5.0.

**Comment by zertosh** [comment]
Thanks @marudor! I'll clean this up a bit in the subsequent commit.

**Comment by zertosh** [comment]
eslint-plugin-flow-vars@0.2.0 is eslint 2.0 compatible

**Pull request merged**
